{
    'name': 'Helpdesk Custom',
    'version': '19.0.1.0.0',
    'summary': 'Full-featured helpdesk: tickets, SLA, teams, ratings, portal, CRM, sales, timesheets, projects and more',
    'category': 'Services/Helpdesk',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': [
        'mail',
        'portal',
        'rating',
        'resource',
        'project',
        'sale',
        'crm',
        'product',
        'hr_timesheet',
    ],
    'data': [
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'data/helpdesk_data.xml',
        'views/helpdesk_ticket_stage_views.xml',
        'views/helpdesk_ticket_type_views.xml',
        'views/helpdesk_ticket_motive_views.xml',
        'views/helpdesk_ticket_category_views.xml',
        'views/helpdesk_ticket_channel_views.xml',
        'views/helpdesk_ticket_tag_views.xml',
        'views/helpdesk_sla_views.xml',
        'views/helpdesk_ticket_views.xml',
        'views/helpdesk_ticket_team_views.xml',
        'views/helpdesk_sla_report_views.xml',
        'views/helpdesk_dashboard_views.xml',
        'views/helpdesk_ticket_templates.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/mail_activity_views.xml',
        'views/project_views.xml',
        'views/sale_order_views.xml',
        'views/crm_lead_views.xml',
        'views/product_views.xml',
        'views/hr_timesheet_views.xml',
        'wizard/helpdesk_ticket_duplicate_wizard_views.xml',
        'wizard/helpdesk_ticket_merge_views.xml',
        'wizard/helpdesk_ticket_create_lead_views.xml',
        'wizard/helpdesk_ticket_link_sale_order_views.xml',
        'report/report_timesheet_templates.xml',
        'views/helpdesk_ticket_menu.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
