from . import helpdesk_ticket_stage
from . import helpdesk_ticket_type
from . import helpdesk_ticket_motive
from . import helpdesk_ticket_category
from . import helpdesk_ticket_tag
from . import helpdesk_ticket_channel
from . import helpdesk_sla
from . import helpdesk_ticket_sla
from . import helpdesk_sla_report
from . import helpdesk_ticket_team
from . import helpdesk_ticket
from . import mail_activity
from . import mail_thread
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import project_project
from . import project_task
from . import project_milestone
from . import sale_order
from . import crm_lead
from . import product
from . import account_analytic_line
